const TH_FIELDS = {
    'Territory type': 'Homes',
    'Territory number': 136,
    'Location type': 'House',
    Language: 'English',
    Status: 'Do not call',
    Latitude: 35.7704,
    Longitude: -78.8544,
    Address: '102 Turk House Lane, Cary, NC',
    Number: 102,
    Street: 'Turk House Lane',
    City: 'Cary',
    County: '',
    'Postal code': 27519,
    State: 'NC',
    'Country code': 'US',
    Notes: '',
    'Last visited': '',
    'Last updated': 42904.6829282407,
    'Date created': 42904.6807060185
};

const TH_BRIDGE_MAP = {
    id: null,
    territoryType: 'Territory type',
    territoryId: 'Territory number',
    locationType: 'Location type',
    language: 'Language',
    contactType: 'Status',
    latitude: 'Latitude',
    longitude: 'Longitude',
    addressDescription: 'Address',
    addressLine1: 'Number',
    addressLine2: null,
    street: 'Street',
    city: 'City',
    postalCode: 'Postal code',
    state: 'State',
    countryCode: 'Country code',
    notes: 'Notes',
    lastVisit: 'Last visited',
    updated: 'Last updated',
    created: 'Date created',
};

const ALBA_FIELDS = {
    Address_ID: '7182625',
    Suite: '',
    Address: '1175 Alsace Dr.',
    City: 'Apex',
    Province: 'NC',
    Postal_code: '27502',
    Country: 'USA',
    Notes: '',
    Kind: 'Foreign-language',
    Status: '',
    Account: 'Triangle Park Hindi',
    Language: 'Hindi'
};

const ALBA_BRIDGE_MAP = {
    id: 'Address_ID',
    territoryType: null,
    territoryId: null,
    locationType: 'Account',
    language: 'Language',
    contactType: 'Kind',
    latitude: null,
    longitude: null,
    addressDescription: 'Address',
    addressLine1: null,
    addressLine2: 'Suite',
    street: 'Address',
    city: 'City',
    postalCode: 'Postal_code',
    state: 'Province',
    countryCode: 'Country',
    notes: 'Notes',
    lastVisit: null,
    updated: null,
    created: null,
};
