// TODO Rename to attributes.js
exports.FOREIGN_LANGUAGE = 'FOREIGN_LANGUAGE';
exports.DO_NOT_CALL = 'DO_NOT_CALL';
exports.PENDING = 'PENDING';
exports.PLACE_TYPE_SINGLE_FAMILY = 'PLACE_TYPE_SINGLE_FAMILY';
exports.PLACE_TYPE_MULTI_FAMILY = 'PLACE_TYPE_MULTI_FAMILY';
exports.PLACE_TYPE_BUSINESS = 'PLACE_TYPE_BUSINESS';
exports.PLACE_TYPE_PUBLIC = 'PLACE_TYPE_PUBLIC';
